services:
  # create localstack for aws simulation and mock_rds for aws rds
  
  localstack:
    container_name: localstack_main
    image: localstack/localstack:3.8.0
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3,lambda
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - local_aws

  mock_rds:
    container_name: mock_rds_postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - local_aws

networks:
  local_aws:
    driver: bridge

volumes:
  db_data:

